config/routes.rb
Devex2::Application.routes.draw do
  get '/home', to: 'posts#index'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/search', to: 'posts#search'

  get '/downloads/:id', to: 'downloads#get', as: 'download'
  
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  resources :posts, only: [:index, :show]
  resources :tags, only: [:index]

  namespace :admin do
    resources :users, only: [:show]
    resources :posts
  end

  root 'posts#index'

end

app/views/shared/_default_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('devex.title'), root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search" action="/search" method="get">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="<%= t('post.search') %>" name="q" id="navbar-search-post">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('user.profile'), current_user %></li>
            <% if current_user.admin? %>
              <li><%= link_to t('user.admin.dashboard'), admin_user_path(current_user) %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to t('user.logout.text'), logout_path %></li>
          </ul>
        </li>
        <% else %>
          <li dropdown="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('user.login.text') %> <span class="caret"></span></a>
            <div class="dropdown-menu" style="padding: 10px;">
              <%= form_for(:session, url: sessions_path, html: {role: 'form'}) do |f| %>
                <div class="form-group">
                  <%= f.text_field :email, class: 'form-control input-sm',
                      placeholder: t('user.email') %>
                </div>
                <div class="form-group">
                  <%= f.password_field :password, class: 'form-control input-sm',
                      placeholder: t('user.password') %>
                </div>
                <%= f.submit t('user.login.text'), class: 'btn btn-default btn-sm' %> |
                <%= link_to t('user.register.text'), signup_path %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_footer.html.erb
<footer class="footer">
  &copy;2014 Elsif | 
  <%= link_to 'Aref Aslani', 'https://github.com/arefaslani' %> | 
  <%= link_to 'Pouya Gharib Pour', 'http://github.com/psparabara' %>
</footer>

app/views/shared/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= alert_box value, dismissible: true, context: key %>
<% end %>