config/routes.rb
Devex2::Application.routes.draw do
  get '/home', to: 'posts#index'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/search', to: 'posts#search'

  get '/downloads/:id', to: 'downloads#get', as: 'download'
  
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  resources :posts, only: [:index, :show]
  resources :tags, only: [:index]

  namespace :admin do
    resources :users, only: [:show]
    resources :posts
  end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  #mount_uploader :image, PostImageUploader
  #mount_uploader :video, PostVideoUploader

  validates :title, presence: true
  validates :digest, presence: true
  #validates :video, presence: true

  def self.find_by_tag(tag)
    Post.where("'#{tag}' = ANY (tags)")
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_filter :check_signed_in

    def index
      @posts = current_user.posts
    end

    def new
      @post = Post.new 
      begin
        authorize @post
      rescue Pundit::NotAuthorizedError
        flash[:warning] = t('authorization.errors.post.new')
        redirect_to current_user
      end
    end

    def create
      @post = current_user.posts.new(post_params)
      f = File.open(Rails.root.to_s + "/app/tst.mp4", 'wb')
      f.write(params[:post][:video].read)
      f.close
      @post.video = "ksdfld.mp4"
      begin
        @post.save
        flash[:success] = t('post.create.success')
        redirect_to admin_user_path(current_user)
      rescue
        flash.now[:danger] = t('post.create.failure')
        render :new
      end
    end

    def edit
      @post = Post.find(params[:id])
      begin
        authorize @post
      rescue Pundit::NotAuthorizedError
        flash[:warning] = t('authorization.errors.post.edit')
        redirect_to current_user
      end
    end

    def update
      @post = Post.find(params[:id])
      @post.update_attributes(post_params)
      begin
        @post.save!
        flash[:success] = t('post.edit.success')
        redirect_to admin_user_path(current_user)
      rescue
        render :edit
        flash.now[:danger] = t('post.create.failure')
      end
    end

    def destroy
      Post.find(params[:id]).destroy!
      flash[:success] = t('post.delete.success')
      redirect_to admin_user_path(current_user)
    end

    private

    def check_signed_in
      unless signed_in?
        flash[:warning] = t('authorization.errors.signin')
        redirect_to login_path(redirect_url: request.original_url)
      end
    end

    def post_params
      temp = params.require(:post).permit(:title, :digest, :tags, :image, :video)
      temp[:tags] = temp[:tags].split(',') if temp[:tags]
      return temp
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('id DESC').page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def search
    # add array of posts returned by where clause to posts returned by find_by_tag
    @posts = Post.where("LOWER(title) LIKE LOWER('%#{params[:q]}%')") | Post.find_by_tag(params[:q])

    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @posts }
    end
  end

  private

  def check_signed_in
    unless signed_in?
      flash[:warning] = t('authorization.errors.signin')
      redirect_to login_path(redirect_url: request.original_url)
    end
  end

  def post_params
    params.require(:post).permit(:title, :digest)
  end

  def default_serializer_options
    {root: false}
  end
end  

app/views/posts/_post.html.erb
<article itemscope itemtype="http://schema.org/BlogPosting" class="post">
  <section>
    <span class="hidden-xs">
    
    </span>
    <header>
      <h1 itemprop="about"><%= link_to post.title, post_path(post) %></h1>
      <strong class="date"><%= post.created_at.to_date.to_j %></strong>
      <% if current_user && current_user.admin? %>
      <nav class="post-control-links">
        <%= link_to t('post.delete.text'), admin_post_path(post), method: :delete, 
        data: { confirm: t('post.delete.confirmation') },
        class: 'btn btn-danger btn-xs' %>
        <%= link_to t('post.edit.text'), edit_admin_post_path(post),
        class: 'btn btn-primary btn-xs' %>
      </nav>
      <% end %>
    </header>
    <p itemprop="articleBody">
      <%= post.digest %>
      <br>
      <span class="metadata"></span>
    </p>
  </section>
  <div class="clearfix"></div>
  <nav>
    <ul class="post-tags">
    <% post.tags.each do |tag| %>
      <li><%= link_to tag, tags_path(tag: tag) %></li>
    <% end %>
    </ul>
  </nav>
  <div class="clearfix"></div>
</article>

app/views/posts/index.html.erb
<%= content_for(:title, full_title(t('post.index'))) %>
<%= render @posts %>
<div class="pagination-container">
<%= paginate @posts %>
</div>

app/views/posts/search.html.erb
<%= content_for(:title, full_title(t('post.search'))) %>
<%= render @posts %>

app/views/posts/show.html.erb
<%= content_for(:title, full_title(@post.title)) %>
<%= render @post %>

<%= link_to 'دانلود', download_path(@post.id), title: metadata_for(@post.video.path), "data-toggle" => "tooltip", "data-placement" => "left" %>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'arefaslani-devex'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>